import imgFront from "../assets/front.jpg";
import imgBack from "../assets/back.jpg";
import imgLeft from "../assets/left.jpg";
import imgRight from "../assets/right.jpg";
import dalat from "../assets/da-lat.jpg";
import hanoi from "../assets/ha-noi.jpg";
import hcm from "../assets/ho-chi-minh-city.jpg";
import qn from "../assets/quang-ninh.jpg";

export const mockNotice = [
  {
    id: 1,
    type: "trip_cancel",
    title: "Chủ xe hủy chuyến",
    message:
      "Chủ xe Trần Nguyễn Hải đã hủy chuyến đi HEC6SXBY, xe HYUNDAI CUSTIN LUXURY 2024, T5 21:00 24/04/2025 - T6 20:00 25/04/2025.",
    time: "19 giờ trước",
    read: false,
  },
  {
    id: 2,
    type: "trip_cancel",
    title: "Chủ xe hủy chuyến",
    message:
      "Chủ xe PHẠM VĂN PHƯƠNG đã hủy chuyến đi FVY4EYR9, xe CHEVROLET CRUZE 2018, T5 21:00 24/04/2025 - T6 20:00 25/04/2025.",
    time: "19 giờ trước",
    read: false,
  },
  {
    id: 3,
    type: "approval",
    title: "Kiểm duyệt xe",
    message: "Yêu cầu đăng kí xe 98D-234567 bị từ chối phê duyệt.",
    time: "1 ngày trước",
    read: false,
  },
  // Add more notifications to test scrolling
  {
    id: 4,
    type: "trip_cancel",
    title: "Chủ xe hủy chuyến",
    message:
      "Chủ xe Nguyễn Văn A đã hủy chuyến đi ABC1234, xe TOYOTA VIOS 2022, T2 09:00 22/04/2025 - T3 18:00 23/04/2025.",
    time: "2 ngày trước",
    read: false,
  },
  {
    id: 5,
    type: "approval",
    title: "Kiểm duyệt xe",
    message: "Yêu cầu đăng kí xe 51F-678910 đã được phê duyệt.",
    time: "3 ngày trước",
    read: true,
  },
  {
    id: 6,
    type: "trip_cancel",
    title: "Thông báo hệ thống",
    message:
      "Cập nhật chính sách mới về việc thuê xe trên Mioto. Vui lòng xem chi tiết tại đây.",
    time: "4 ngày trước",
    read: true,
  },
];

export const mockCars = [
  {
    id: "KE7XZ6",
    name: "FORD ECOSPORT 2019",
    images: [imgFront, imgBack, imgLeft, imgRight],
    type: "Số tự động",
    seats: 4,
    fuel: "Xăng",
    location: "Quận Bắc Từ Liêm, TP. Hà Nội",
    rating: 4.6,
    trips: 72,
    originalPrice: 1029000,
    discountedPrice: 856000,
    noDeposit: true,
    transmission: "Số tự động",
    fuelConsumption: "7L/100km",
    features: ["ETC"],
    description: "",
    owner: {
      id: "U6D2QF",
      name: "NGUYỄN TRƯỜNG THIÊN LỘC",
      avatar: "https://ext.same-assets.com/3428373608/114987653.jpeg",
      rating: 5.0,
      trips: 46,
      responseRate: 100,
      responseTime: "5 phút",
      approvalRate: 100,
    },
    reviews: [
      {
        id: "R1",
        user: {
          id: "U9HNCF",
          name: "Võ Mộng",
          avatar: "https://ext.same-assets.com/2093811107/2392010464.png",
        },
        rating: 5,
        comment: "Chủ xe dễ thương, thủ tục đơn giản",
        date: "16/03/2025",
      },
    ],
  },
  {
    id: "KF8KNF",
    name: "MITSUBISHI XPANDER 2020",
    images: [imgFront, imgBack, imgLeft, imgRight],
    type: "Số tự động",
    seats: 7,
    fuel: "Xăng",
    location: "Quận Bắc Từ Liêm, TP. Hà Nội",
    rating: 4.8,
    trips: 9,
    originalPrice: 976000,
    discountedPrice: 856000,
    discount: 14,
    transmission: "Số tự động",
    fuelConsumption: "8L/100km",
    features: ["ETC"],
    description: "",
    owner: {
      id: "U6D2QF",
      name: "NGUYỄN TRƯỜNG THIÊN LỘC",
      avatar: "https://ext.same-assets.com/3428373608/114987653.jpeg",
      rating: 5.0,
      trips: 46,
      responseRate: 100,
      responseTime: "5 phút",
      approvalRate: 100,
    },
    reviews: [],
  },
  {
    id: "KJMSFZ",
    name: "TOYOTA INNOVA 2018",
    images: [imgFront, imgBack, imgLeft, imgRight],
    type: "Số sàn",
    seats: 8,
    fuel: "Xăng",
    location: "Quận Bắc Từ Liêm, TP. Hà Nội",
    rating: 4.0,
    trips: 1,
    originalPrice: 871000,
    discountedPrice: 751000,
    discount: 16,
    delivery: true,
    hourlyPrice: 523000,
    transmission: "Số sàn",
    fuelConsumption: "9L/100km",
    features: ["ETC"],
    description: "",
    owner: {
      id: "U6D2QF",
      name: "NGUYỄN TRƯỜNG THIÊN LỘC",
      avatar: "https://ext.same-assets.com/3428373608/114987653.jpeg",
      rating: 5.0,
      trips: 46,
      responseRate: 100,
      responseTime: "5 phút",
      approvalRate: 100,
    },
    reviews: [],
  },
  {
    id: "K5M5NY",
    name: "TOYOTA VELOZ CROSS 2022",
    images: [
      "https://ext.same-assets.com/3352344234/2850139167.jpeg",
      "https://ext.same-assets.com/3352344234/1235292273.jpeg",
      "https://ext.same-assets.com/3352344234/1023356755.jpeg",
    ],
    type: "Số tự động",
    seats: 7,
    fuel: "Xăng",
    location: "Quận Bắc Từ Liêm, TP. Hà Nội",
    rating: 5.0,
    trips: 46,
    originalPrice: 1139000,
    discountedPrice: 1019000,
    discount: 12,
    delivery: true,
    noDeposit: true,
    transmission: "Số tự động",
    fuelConsumption: "8L/100km",
    features: ["ETC"],
    description: "TOYOTA VELOZ CROSS 2022",
    owner: {
      id: "U6D2QF",
      name: "NGUYỄN TRƯỜNG THIÊN LỘC",
      avatar: "https://ext.same-assets.com/3428373608/114987653.jpeg",
      rating: 5.0,
      trips: 46,
      responseRate: 100,
      responseTime: "5 phút",
      approvalRate: 100,
    },
    reviews: [
      {
        id: "R1",
        user: {
          id: "U9HNCF",
          name: "Võ Mộng",
          avatar: "https://ext.same-assets.com/2093811107/2392010464.png",
        },
        rating: 5,
        comment: "Chủ xe dễ thương, thủ tục đơn giản",
        date: "16/03/2025",
      },
      {
        id: "R2",
        user: {
          id: "UN4285",
          name: "Nguyễn Duy Thắng",
          avatar: "https://ext.same-assets.com/2093811107/2392010464.png",
        },
        rating: 5,
        comment: "anh chủ thân thiện, thủ tục nhanh gọn lẹ",
        date: "01/03/2025",
      },
    ],
  },
];

export const mockCarData = [
  {
    id: 1,
    name: "HYUNDAI GRAND I20",
    year: 2010,
    image: imgLeft,
    seats: 5,
    location: "Quận 1, TP. Hồ Chí Minh",
    rating: 5.0,
    trips: 42,
    price: 415000,
    hourlyPrice: 309000,
    discount: 19,
  },
  {
    id: 2,
    name: "TOYOTA INNOVA",
    year: 2016,
    image: imgLeft,
    seats: 8,
    location: "Quận 3, TP. Hồ Chí Minh",
    rating: 5.0,
    trips: 38,
    price: 599000,
    hourlyPrice: 439000,
  },
  {
    id: 3,
    name: "HYUNDAI ACCENT",
    year: 2023,
    image: imgLeft,
    seats: 5,
    location: "Quận 5, TP. Hồ Chí Minh",
    rating: 5.0,
    trips: 29,
    price: 635000,
    hourlyPrice: 441000,
    deliveryOption: true,
  },
  {
    id: 4,
    name: "MITSUBISHI XPANDER",
    year: 2023,
    image: imgLeft,
    seats: 7,
    location: "Quận 4, TP. Hồ Chí Minh",
    rating: 5.0,
    trips: 100,
    price: 730000,
    originalPrice: 850000,
    discount: 16,
  },
  {
    id: 5,
    name: "TOYOTA VIOS",
    year: 2024,
    image: imgLeft,
    seats: 4,
    location: "Quận 1, TP. Hồ Chí Minh",
    rating: 5.0,
    trips: 34,
    price: 726000,
    discount: 12,
  },
  {
    id: 6,
    name: "KIA SEDONA PREMIUM",
    year: 2019,
    image: imgLeft,
    seats: 7,
    location: "Quận 1, TP. Hồ Chí Minh",
    rating: 5.0,
    trips: 64,
    price: 1180000,
    discount: 13,
  },
  {
    id: 7,
    name: "KIA SEDONA PREMIUM",
    year: 2017,
    image: imgLeft,
    seats: 7,
    location: "Quận 1, TP. Hồ Chí Minh",
    rating: 5.0,
    trips: 23,
    price: 1118000,
    discount: 10,
  },
  {
    id: 8,
    name: "LEXUS IS250",
    year: 2009,
    image: imgLeft,
    seats: 4,
    location: "Quận 1, TP. Hồ Chí Minh",
    rating: 4.9,
    trips: 110,
    price: 1456000,
    discount: 6,
  },
  {
    id: 9,
    name: "HYUNDAI GRAND I20",
    year: 2010,
    image: imgLeft,
    seats: 5,
    location: "Quận 1, TP. Hồ Chí Minh",
    rating: 5.0,
    trips: 42,
    price: 415000,
    hourlyPrice: 309000,
    discount: 19,
  },
  {
    id: 10,
    name: "TOYOTA INNOVA",
    year: 2016,
    image: imgLeft,
    seats: 8,
    location: "Quận 3, TP. Hồ Chí Minh",
    rating: 5.0,
    trips: 38,
    price: 599000,
    hourlyPrice: 439000,
  },
  {
    id: 11,
    name: "HYUNDAI ACCENT",
    year: 2023,
    image: imgLeft,
    seats: 5,
    location: "Quận 5, TP. Hồ Chí Minh",
    rating: 5.0,
    trips: 29,
    price: 635000,
    hourlyPrice: 441000,
    deliveryOption: true,
  },
  {
    id: 12,
    name: "MITSUBISHI XPANDER",
    year: 2023,
    image: imgLeft,
    seats: 7,
    location: "Quận 4, TP. Hồ Chí Minh",
    rating: 5.0,
    trips: 100,
    price: 730000,
    originalPrice: 850000,
    discount: 16,
  },
  {
    id: 13,
    name: "TOYOTA VIOS",
    year: 2024,
    image: imgLeft,
    seats: 4,
    location: "Quận 1, TP. Hồ Chí Minh",
    rating: 5.0,
    trips: 34,
    price: 726000,
    discount: 12,
  },
  {
    id: 14,
    name: "KIA SEDONA PREMIUM",
    year: 2019,
    image: imgLeft,
    seats: 7,
    location: "Quận 1, TP. Hồ Chí Minh",
    rating: 5.0,
    trips: 64,
    price: 1180000,
    discount: 13,
  },
  {
    id: 15,
    name: "KIA SEDONA PREMIUM",
    year: 2017,
    image: imgLeft,
    seats: 7,
    location: "Quận 1, TP. Hồ Chí Minh",
    rating: 5.0,
    trips: 23,
    price: 1118000,
    discount: 10,
  },
  {
    id: 16,
    name: "LEXUS IS250",
    year: 2009,
    image: imgLeft,
    seats: 4,
    location: "Quận 1, TP. Hồ Chí Minh",
    rating: 4.9,
    trips: 110,
    price: 1456000,
    discount: 6,
  },
];

export const mockPromotions = [
  {
    id: "P1",
    title: "Ưu đãi tháng 4",
    imageUrl: "https://ext.same-assets.com/2093811107/2340204415.jpeg",
    description: "Giảm 10% cho chuyến đi đầu tiên",
    code: "WELCOME10",
    discount: 10,
    startDate: "01/04/2025",
    endDate: "30/04/2025",
  },
  {
    id: "P2",
    title: "Ưu đãi cuối tuần",
    imageUrl: "https://ext.same-assets.com/2093811107/1290257754.jpeg",
    description: "Giảm 15% cho thuê xe vào cuối tuần",
    code: "WEEKEND15",
    discount: 15,
    startDate: "01/04/2025",
    endDate: "30/06/2025",
  },
  {
    id: "P3",
    title: "Ưu đãi ngày lễ",
    imageUrl: "https://ext.same-assets.com/2093811107/3852245714.jpeg",
    description: "Giảm 20% cho thuê xe vào các ngày lễ",
    code: "HOLIDAY20",
    discount: 20,
    startDate: "01/04/2025",
    endDate: "31/12/2025",
  },
  {
    id: "P4",
    title: "Ưu đãi dài hạn",
    imageUrl: "https://ext.same-assets.com/2093811107/143930812.jpeg",
    description: "Giảm 25% cho thuê xe dài hạn",
    code: "LONGTERM25",
    discount: 25,
    startDate: "01/04/2025",
    endDate: "31/12/2025",
  },
];

export const mockLocations = [
  {
    id: "HoChiMinh",
    name: "TP. Hồ Chí Minh",
    cars: 5000,
    imageUrl: hcm,
  },
  {
    id: "HaNoi",
    name: "Hà Nội",
    cars: 2500,
    imageUrl: hanoi,
  },
  {
    id: "DaLat",
    name: "Đà Lạt",
    cars: 500,
    imageUrl: dalat,
  },
  {
    id: "QuangNinh",
    name: "Quảng Ninh",
    cars: 500,
    imageUrl: qn,
  },
];
